// 앱 최초 실행 시 기본 그룹 3개 시드

import { db } from "./client";
import { groups, logPersons, logs, memos, persons, todos } from "./schema";

export const DEFAULT_GROUPS = [
  {
    name: "미설정",
    color: "#ADB5BD", // 회색톤으로 설정하여 '없음'의 느낌을 강조
    emoji: "⬛", // 비어있는 것보다 기본 이모지가 있는 것이 UI상 깔끔합니다
    isDefault: true,
    sortOrder: 0,
  },
  {
    name: "가족",
    color: "#FF6B6B",
    emoji: "🏠",
    isDefault: true,
    sortOrder: 1,
  },
  {
    name: "친구",
    color: "#4ECDC4",
    emoji: "👥",
    isDefault: true,
    sortOrder: 2,
  },
  {
    name: "회사",
    color: "#45B7D1",
    emoji: "💼",
    isDefault: true,
    sortOrder: 3,
  },
  {
    name: "지인",
    color: "#FFA07A", // 기존 노란색보다 가독성이 좋은 살구색 계열 추천
    emoji: "🤝",
    isDefault: true,
    sortOrder: 4,
  },
];

export async function seedDefaultGroups() {
  const existing = await db.select().from(groups);
  if (existing.length > 0) return;
  await db.insert(groups).values(DEFAULT_GROUPS);
}

export const REPEAT_OPTIONS = [
  { label: "없음", value: "none" },
  { label: "매일", value: "daily" },
  { label: "매주", value: "weekly" },
  { label: "매월", value: "monthly" },
  { label: "매년", value: "yearly" },
];

export const WEEKDAYS = ["일", "월", "화", "수", "목", "금", "토"];

export const MBTI_OPTIONS = [
  "INTJ",
  "INTP",
  "ENTJ",
  "ENTP",
  "INFJ",
  "INFP",
  "ENFJ",
  "ENFP",
  "ISTJ",
  "ISFJ",
  "ESTJ",
  "ESFJ",
  "ISTP",
  "ISFP",
  "ESTP",
  "ESFP",
];

export const PRESET_COLORS = [
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#96CEB4",
  "#FFEAA7",
  "#DDA0DD",
  "#98D8C8",
  "#F7DC6F",
];

export const ANNIVERSARY_PRESETS = ["생일", "결혼", "입사", "퇴사", "이사"];

// 개발용 샘플 데이터 삽입 — 디버그 모드 개발 도구에서 호출
export async function seedSampleData() {
  const allGroups = await db.select().from(groups);
  const g = (name: string) =>
    allGroups.find((g) => g.name === name)?.id ?? allGroups[0].id;

  const familyId = g("가족");
  const friendId = g("친구");
  const workId = g("회사");
  const acquaintId = g("지인");
  const unsetId = g("미설정");

  const d = (y: number, m: number, day: number) => new Date(y, m - 1, day);
  const t = (...tags: string[]) => JSON.stringify(tags);

  // 인물 100명 — p[0]~p[49] 기존, p[50]~p[99] 신규
  const p = await db
    .insert(persons)
    .values([
      // ── 기존 50명 ─────────────────────────────────────────
      {
        name: "김민수",
        groupId: familyId,
        mbti: "ISTJ",
        memo: "형, 서울 거주",
        tags: t("가족"),
        metAt: "2010-03-01",
        contactInterval: 7,
        isPinned: true,
      },
      {
        name: "박지원",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "1995-03-22",
        tags: t("오랜친구"),
        metAt: "2013-03-22",
        contactInterval: 30,
      },
      {
        name: "이수진",
        groupId: workId,
        memo: "팀장, 디자인 담당",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "최현우",
        groupId: acquaintId,
        mbti: "ENTP",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "정다은",
        groupId: friendId,
        birthDate: "1996-08-10",
        tags: t("오랜친구"),
        metAt: "2014-08-10",
        contactInterval: 30,
      },
      {
        name: "한지민",
        groupId: friendId,
        mbti: "INFP",
        birthDate: "1998-02-14",
        tags: t("오랜친구"),
        metAt: "2016-02-14",
        contactInterval: 30,
      },
      {
        name: "오승준",
        groupId: workId,
        mbti: "INTJ",
        memo: "개발팀 시니어",
        tags: t("직장동료", "멘토"),
        contactInterval: 30,
      },
      {
        name: "서예린",
        groupId: familyId,
        mbti: "ISFJ",
        birthDate: "1990-07-04",
        memo: "누나, 결혼함",
        tags: t("가족"),
        metAt: "2005-01-01",
        contactInterval: 7,
      },
      {
        name: "임도현",
        groupId: friendId,
        mbti: "ESTP",
        birthDate: "1997-11-30",
        tags: t("오랜친구"),
        metAt: "2015-11-30",
        contactInterval: 30,
      },
      {
        name: "강민지",
        groupId: workId,
        mbti: "ENFJ",
        memo: "인사팀 매니저",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "윤성호",
        groupId: acquaintId,
        mbti: "INTP",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "황주연",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "1996-05-17",
        tags: t("오랜친구"),
        metAt: "2014-05-17",
        contactInterval: 30,
      },
      {
        name: "송재원",
        groupId: workId,
        mbti: "ISTJ",
        memo: "기획팀",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "신예지",
        groupId: familyId,
        mbti: "INFJ",
        birthDate: "1993-12-25",
        memo: "사촌동생",
        tags: t("가족"),
        metAt: "2000-01-01",
        contactInterval: 30,
      },
      {
        name: "전민혁",
        groupId: acquaintId,
        mbti: "ISTP",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "조아연",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "2000-04-08",
        tags: t("오랜친구"),
        metAt: "2018-04-08",
        contactInterval: 30,
      },
      {
        name: "류승현",
        groupId: workId,
        mbti: "ENTJ",
        memo: "부장님",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "배소영",
        groupId: acquaintId,
        mbti: "ISFP",
        memo: "헬스장에서 만난 지인",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "고다현",
        groupId: friendId,
        mbti: "ESFJ",
        birthDate: "1998-09-21",
        tags: t("오랜친구"),
        metAt: "2016-09-21",
        contactInterval: 30,
      },
      {
        name: "남지훈",
        groupId: workId,
        mbti: "INTP",
        memo: "데이터팀",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "문세연",
        groupId: familyId,
        mbti: "ESTJ",
        birthDate: "1985-03-15",
        memo: "형수님",
        tags: t("가족"),
        metAt: "2012-06-01",
        contactInterval: 7,
      },
      {
        name: "양현준",
        groupId: friendId,
        mbti: "ENFJ",
        tags: t("오랜친구"),
        metAt: "2015-03-01",
        contactInterval: 30,
      },
      {
        name: "차지수",
        groupId: acquaintId,
        mbti: "INFP",
        birthDate: "1999-06-30",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "마해린",
        groupId: workId,
        mbti: "ISTP",
        memo: "디자인팀",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "노태민",
        groupId: friendId,
        mbti: "ESTP",
        birthDate: "1997-01-12",
        tags: t("오랜친구"),
        metAt: "2015-01-12",
        contactInterval: 30,
      },
      {
        name: "허수빈",
        groupId: familyId,
        mbti: "ISFJ",
        memo: "어머니",
        tags: t("가족"),
        metAt: "1993-01-01",
        contactInterval: 7,
        isPinned: true,
      },
      {
        name: "성유진",
        groupId: workId,
        mbti: "ENTP",
        memo: "마케팅팀",
        tags: t("직장동료"),
        contactInterval: 30,
      },
      {
        name: "우지후",
        groupId: acquaintId,
        mbti: "INTJ",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "민채원",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "2001-08-25",
        tags: t("오랜친구"),
        metAt: "2019-08-25",
        contactInterval: 30,
      },
      {
        name: "표상우",
        groupId: workId,
        mbti: "INFJ",
        memo: "멘토",
        tags: t("멘토", "직장동료"),
        contactInterval: 30,
        isPinned: true,
      },
      {
        name: "권나영",
        groupId: friendId,
        mbti: "ESFJ",
        birthDate: "1997-04-15",
        tags: t("연인"),
        metAt: "2023-04-15",
        contactInterval: 7,
        isPinned: true,
      },
      {
        name: "김태양",
        groupId: workId,
        mbti: "ENTJ",
        memo: "스타트업 공동창업자",
        tags: t("직장동료", "멘토"),
        metAt: "2022-07-01",
        contactInterval: 30,
      },
      {
        name: "이민호",
        groupId: friendId,
        mbti: "ISTP",
        birthDate: "1996-09-08",
        tags: t("오랜친구"),
        metAt: "2014-09-08",
        contactInterval: 30,
      },
      {
        name: "박서연",
        groupId: familyId,
        mbti: "ISFJ",
        birthDate: "2003-11-22",
        memo: "막내 여동생",
        tags: t("가족"),
        metAt: "2003-11-22",
        contactInterval: 7,
      },
      {
        name: "최준혁",
        groupId: acquaintId,
        mbti: "ENTP",
        memo: "독서 모임에서 만남",
        tags: t("온라인친구"),
        metAt: "2024-01-15",
        contactInterval: 90,
      },
      {
        name: "장수빈",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "1999-07-03",
        tags: t("오랜친구"),
        metAt: "2017-07-03",
        contactInterval: 30,
      },
      {
        name: "한지호",
        groupId: workId,
        mbti: "INTP",
        memo: "개발팀 후배",
        tags: t("직장동료"),
        metAt: "2023-03-02",
        contactInterval: 30,
      },
      {
        name: "임채은",
        groupId: friendId,
        mbti: "INFP",
        birthDate: "2000-12-01",
        tags: t("오랜친구"),
        metAt: "2018-12-01",
        contactInterval: 30,
      },
      {
        name: "윤재원",
        groupId: acquaintId,
        mbti: "ISTJ",
        memo: "같은 아파트 주민",
        tags: t("온라인친구"),
        contactInterval: 90,
      },
      {
        name: "강지선",
        groupId: familyId,
        mbti: "ESFJ",
        birthDate: "1968-05-08",
        memo: "이모",
        tags: t("가족"),
        metAt: "1993-01-01",
        contactInterval: 30,
      },
      {
        name: "조현기",
        groupId: workId,
        mbti: "ESTJ",
        memo: "전 직장 동료, 현재 타사",
        tags: t("직장동료"),
        metAt: "2020-04-01",
        contactInterval: 90,
      },
      {
        name: "문하린",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "1998-06-18",
        tags: t("오랜친구"),
        metAt: "2016-06-18",
        contactInterval: 30,
      },
      {
        name: "신동욱",
        groupId: acquaintId,
        mbti: "INTJ",
        memo: "온라인 커뮤니티 인연",
        tags: t("온라인친구"),
        metAt: "2023-11-10",
        contactInterval: 90,
      },
      {
        name: "우서진",
        groupId: friendId,
        mbti: "ENFJ",
        birthDate: "1997-02-28",
        tags: t("오랜친구"),
        metAt: "2015-02-28",
        contactInterval: 30,
      },
      {
        name: "배민아",
        groupId: workId,
        mbti: "ISFP",
        memo: "UX 리서처",
        tags: t("직장동료"),
        metAt: "2024-01-02",
        contactInterval: 30,
      },
      {
        name: "전지혁",
        groupId: familyId,
        mbti: "ESTP",
        memo: "삼촌",
        tags: t("가족"),
        metAt: "1993-01-01",
        contactInterval: 30,
      },
      {
        name: "송아름",
        groupId: friendId,
        mbti: "INFJ",
        birthDate: "1996-10-14",
        tags: t("오랜친구"),
        metAt: "2014-10-14",
        contactInterval: 30,
      },
      {
        name: "양서준",
        groupId: workId,
        mbti: "ENFP",
        memo: "프리랜서 협업",
        tags: t("직장동료"),
        metAt: "2024-06-01",
        contactInterval: 90,
      },
      {
        name: "차민경",
        groupId: acquaintId,
        mbti: "ISFJ",
        memo: "학원 동창",
        tags: t("오랜친구"),
        metAt: "2008-03-01",
        contactInterval: 90,
      },
      {
        name: "허태현",
        groupId: workId,
        mbti: "ENTJ",
        memo: "투자자, 비즈니스 파트너",
        tags: t("멘토"),
        metAt: "2023-09-15",
        contactInterval: 30,
      },
      // ── 신규 50명 ─────────────────────────────────────────
      {
        name: "김현아",
        groupId: friendId,
        mbti: "ENFJ",
        birthDate: "1997-06-15",
        tags: t("오랜친구"),
        metAt: "2015-06-15",
        contactInterval: 30,
      },
      {
        name: "이준호",
        groupId: workId,
        mbti: "INTJ",
        memo: "백엔드 개발자",
        tags: t("직장동료"),
        metAt: "2023-01-10",
        contactInterval: 30,
      },
      {
        name: "박민서",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "2000-03-05",
        tags: t("오랜친구"),
        metAt: "2018-03-05",
        contactInterval: 30,
      },
      {
        name: "최유진",
        groupId: acquaintId,
        mbti: "INFP",
        memo: "독서 모임 멤버",
        tags: t("온라인친구"),
        metAt: "2024-02-20",
        contactInterval: 90,
      },
      {
        name: "정현준",
        groupId: workId,
        mbti: "ESTJ",
        memo: "QA 엔지니어",
        tags: t("직장동료"),
        metAt: "2022-09-01",
        contactInterval: 30,
      },
      {
        name: "강소영",
        groupId: friendId,
        mbti: "ISFJ",
        birthDate: "1999-10-20",
        tags: t("오랜친구"),
        metAt: "2017-10-20",
        contactInterval: 30,
      },
      {
        name: "윤진호",
        groupId: acquaintId,
        mbti: "ENTP",
        memo: "요리 교실 동기",
        tags: t("온라인친구"),
        metAt: "2024-03-01",
        contactInterval: 90,
      },
      {
        name: "임수연",
        groupId: friendId,
        mbti: "INFJ",
        birthDate: "1998-01-17",
        tags: t("오랜친구"),
        metAt: "2016-01-17",
        contactInterval: 30,
      },
      {
        name: "한동훈",
        groupId: workId,
        mbti: "ISTP",
        memo: "DevOps 엔지니어",
        tags: t("직장동료"),
        metAt: "2023-07-15",
        contactInterval: 30,
      },
      {
        name: "조민수",
        groupId: acquaintId,
        mbti: "ENFP",
        memo: "테니스 동호회 멤버",
        tags: t("온라인친구"),
        metAt: "2023-09-10",
        contactInterval: 90,
      },
      {
        name: "문지호",
        groupId: friendId,
        mbti: "ENTJ",
        birthDate: "1996-12-03",
        tags: t("오랜친구"),
        metAt: "2014-12-03",
        contactInterval: 30,
      },
      {
        name: "신하은",
        groupId: workId,
        mbti: "ESFJ",
        memo: "CS팀 매니저",
        tags: t("직장동료"),
        metAt: "2021-05-03",
        contactInterval: 30,
      },
      {
        name: "배준혁",
        groupId: friendId,
        mbti: "ISTP",
        birthDate: "1997-08-25",
        tags: t("오랜친구"),
        metAt: "2015-08-25",
        contactInterval: 30,
      },
      {
        name: "전소희",
        groupId: acquaintId,
        mbti: "ISFP",
        memo: "요가 원장님",
        tags: t("온라인친구"),
        metAt: "2023-01-15",
        contactInterval: 90,
      },
      {
        name: "류민아",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "2001-05-10",
        tags: t("오랜친구"),
        metAt: "2019-05-10",
        contactInterval: 30,
      },
      {
        name: "고승훈",
        groupId: workId,
        mbti: "ENTJ",
        memo: "CTO",
        tags: t("직장동료", "멘토"),
        metAt: "2022-07-01",
        contactInterval: 30,
      },
      {
        name: "남은지",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "1999-02-22",
        tags: t("오랜친구"),
        metAt: "2017-02-22",
        contactInterval: 30,
      },
      {
        name: "마준혁",
        groupId: acquaintId,
        mbti: "INTP",
        memo: "게임 동료",
        tags: t("온라인친구"),
        metAt: "2022-11-05",
        contactInterval: 90,
      },
      {
        name: "노현아",
        groupId: friendId,
        mbti: "INFJ",
        birthDate: "1998-09-14",
        tags: t("오랜친구"),
        metAt: "2016-09-14",
        contactInterval: 30,
      },
      {
        name: "허진수",
        groupId: workId,
        mbti: "ESTP",
        memo: "영업팀 리더",
        tags: t("직장동료"),
        metAt: "2023-02-01",
        contactInterval: 30,
      },
      {
        name: "성민재",
        groupId: friendId,
        mbti: "INFP",
        birthDate: "2000-07-18",
        tags: t("오랜친구"),
        metAt: "2018-07-18",
        contactInterval: 30,
      },
      {
        name: "우다영",
        groupId: acquaintId,
        mbti: "ISFJ",
        memo: "카페 알바 동기",
        tags: t("온라인친구"),
        metAt: "2021-08-01",
        contactInterval: 90,
      },
      {
        name: "민서준",
        groupId: workId,
        mbti: "ENTP",
        memo: "풀스택 개발자",
        tags: t("직장동료"),
        metAt: "2024-02-01",
        contactInterval: 30,
      },
      {
        name: "표지연",
        groupId: friendId,
        mbti: "ESFJ",
        birthDate: "1997-04-29",
        tags: t("오랜친구"),
        metAt: "2015-04-29",
        contactInterval: 30,
      },
      {
        name: "권태윤",
        groupId: acquaintId,
        mbti: "INTJ",
        memo: "사진 동호회 멤버",
        tags: t("온라인친구"),
        metAt: "2023-10-20",
        contactInterval: 90,
      },
      {
        name: "장채린",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "1999-11-08",
        tags: t("오랜친구"),
        metAt: "2017-11-08",
        contactInterval: 30,
      },
      {
        name: "한수현",
        groupId: workId,
        mbti: "ISFJ",
        memo: "법무팀",
        tags: t("직장동료"),
        metAt: "2022-04-01",
        contactInterval: 30,
      },
      {
        name: "임지훈",
        groupId: friendId,
        mbti: "ESTP",
        birthDate: "1996-06-22",
        tags: t("오랜친구"),
        metAt: "2014-06-22",
        contactInterval: 30,
      },
      {
        name: "윤채연",
        groupId: acquaintId,
        mbti: "INFP",
        memo: "공방 클래스 동기",
        tags: t("온라인친구"),
        metAt: "2024-04-10",
        contactInterval: 90,
      },
      {
        name: "강진우",
        groupId: workId,
        mbti: "ISTJ",
        memo: "보안팀",
        tags: t("직장동료"),
        metAt: "2021-11-01",
        contactInterval: 30,
      },
      {
        name: "조현석",
        groupId: familyId,
        mbti: "ESTP",
        memo: "외삼촌",
        tags: t("가족"),
        metAt: "1993-01-01",
        contactInterval: 30,
      },
      {
        name: "문수진",
        groupId: acquaintId,
        mbti: "ENFJ",
        memo: "봉사활동 동기",
        tags: t("온라인친구"),
        metAt: "2023-05-20",
        contactInterval: 90,
      },
      {
        name: "신태양",
        groupId: workId,
        mbti: "INTP",
        memo: "AI 연구원",
        tags: t("직장동료", "멘토"),
        metAt: "2024-03-15",
        contactInterval: 30,
      },
      {
        name: "배채은",
        groupId: friendId,
        mbti: "ISFP",
        birthDate: "2001-09-30",
        tags: t("오랜친구"),
        metAt: "2019-09-30",
        contactInterval: 30,
      },
      {
        name: "전준서",
        groupId: acquaintId,
        mbti: "ENTP",
        memo: "유튜버",
        tags: t("온라인친구"),
        metAt: "2024-01-05",
        contactInterval: 90,
      },
      {
        name: "류현정",
        groupId: friendId,
        mbti: "ENFJ",
        birthDate: "1998-03-17",
        tags: t("오랜친구"),
        metAt: "2016-03-17",
        contactInterval: 30,
      },
      {
        name: "고민준",
        groupId: workId,
        mbti: "ENTJ",
        memo: "해외사업팀",
        tags: t("직장동료"),
        metAt: "2022-10-01",
        contactInterval: 30,
      },
      {
        name: "남서윤",
        groupId: friendId,
        mbti: "ESFJ",
        birthDate: "1997-07-28",
        tags: t("오랜친구"),
        metAt: "2015-07-28",
        contactInterval: 30,
      },
      {
        name: "마현석",
        groupId: acquaintId,
        mbti: "ISTP",
        memo: "군대 전우",
        tags: t("온라인친구"),
        metAt: "2018-03-01",
        contactInterval: 90,
      },
      {
        name: "노수빈",
        groupId: familyId,
        mbti: "ISFJ",
        birthDate: "1995-05-15",
        memo: "사촌 누나",
        tags: t("가족"),
        metAt: "2005-01-01",
        contactInterval: 30,
      },
      {
        name: "허민지",
        groupId: workId,
        mbti: "ENFP",
        memo: "콘텐츠 크리에이터",
        tags: t("직장동료"),
        metAt: "2023-08-01",
        contactInterval: 30,
      },
      {
        name: "성지원",
        groupId: friendId,
        mbti: "INFJ",
        birthDate: "2000-01-25",
        tags: t("오랜친구"),
        metAt: "2018-01-25",
        contactInterval: 30,
      },
      {
        name: "우준혁",
        groupId: acquaintId,
        mbti: "ESTP",
        memo: "동네 친구",
        tags: t("온라인친구"),
        metAt: "2020-06-15",
        contactInterval: 90,
      },
      {
        name: "민하린",
        groupId: friendId,
        mbti: "ESFP",
        birthDate: "1999-04-02",
        tags: t("오랜친구"),
        metAt: "2017-04-02",
        contactInterval: 30,
      },
      {
        name: "표민수",
        groupId: workId,
        mbti: "ISTJ",
        memo: "재무팀 과장",
        tags: t("직장동료"),
        metAt: "2021-01-04",
        contactInterval: 30,
      },
      {
        name: "권지수",
        groupId: friendId,
        mbti: "INFP",
        birthDate: "1998-08-11",
        tags: t("오랜친구"),
        metAt: "2016-08-11",
        contactInterval: 30,
      },
      {
        name: "장수민",
        groupId: acquaintId,
        mbti: "ENFJ",
        memo: "코딩 부트캠프 동기",
        tags: t("온라인친구"),
        metAt: "2023-06-01",
        contactInterval: 90,
      },
      {
        name: "한민호",
        groupId: friendId,
        mbti: "ISTP",
        birthDate: "1996-11-19",
        tags: t("오랜친구"),
        metAt: "2014-11-19",
        contactInterval: 30,
      },
      {
        name: "임소연",
        groupId: workId,
        mbti: "ESFJ",
        memo: "HR 담당",
        tags: t("직장동료"),
        metAt: "2022-08-15",
        contactInterval: 30,
      },
      {
        name: "윤지민",
        groupId: friendId,
        mbti: "ENFP",
        birthDate: "2001-02-14",
        tags: t("오랜친구"),
        metAt: "2019-02-14",
        contactInterval: 30,
      },
      {
        name: "강태현",
        groupId: unsetId,
        memo: "아직 그룹 미분류",
        tags: t(),
        contactInterval: 90,
      },
    ])
    .returning();

  // 기록 80개 — 2025-04 ~ 2026-05
  const l = await db
    .insert(logs)
    .values([
      // ── 기존 30개 ─────────────────────────────────────────
      {
        title: "가족 저녁 식사",
        logDate: d(2026, 5, 3),
        groupId: familyId,
        memo: "삼겹살 집, 오랜만에 모두 모임",
      },
      { title: "친구들이랑 영화", logDate: d(2026, 5, 7), groupId: friendId },
      {
        title: "팀 회식",
        logDate: d(2026, 5, 9),
        groupId: workId,
        memo: "이자카야, 2차는 노래방",
      },
      {
        title: "지원이 생일파티",
        logDate: d(2026, 5, 12),
        groupId: friendId,
        memo: "케이크 사 갔음",
      },
      { title: "어머니 병원 동행", logDate: d(2026, 5, 14), groupId: familyId },
      {
        title: "현우 커피 미팅",
        logDate: d(2026, 5, 15),
        groupId: acquaintId,
        memo: "스타벅스 강남점",
      },
      {
        title: "수진 팀장 승진 축하",
        logDate: d(2026, 4, 28),
        groupId: workId,
      },
      {
        title: "대학 동창 모임",
        logDate: d(2026, 4, 20),
        groupId: friendId,
        memo: "홍대 맛집 탐방",
      },
      {
        title: "가족 여행 계획 회의",
        logDate: d(2026, 4, 15),
        groupId: familyId,
      },
      {
        title: "다은이랑 전시회",
        logDate: d(2026, 4, 10),
        groupId: friendId,
        memo: "국립현대미술관",
      },
      {
        title: "치맥 번개",
        logDate: d(2026, 4, 5),
        groupId: friendId,
        memo: "종로 치킨집",
      },
      {
        title: "팀 워크숍",
        logDate: d(2026, 3, 28),
        groupId: workId,
        memo: "판교 오피스",
      },
      {
        title: "봄 소풍",
        logDate: d(2026, 3, 22),
        groupId: friendId,
        memo: "한강 피크닉",
      },
      {
        title: "어버이날 선물 전달",
        logDate: d(2026, 3, 15),
        groupId: familyId,
        memo: "카네이션 다발",
      },
      {
        title: "지인 결혼식",
        logDate: d(2026, 3, 8),
        groupId: acquaintId,
        memo: "코엑스 컨벤션홀",
      },
      {
        title: "설 명절 가족 모임",
        logDate: d(2026, 2, 28),
        groupId: familyId,
        memo: "고향 방문, 친척들 만남",
      },
      {
        title: "신입 환영회",
        logDate: d(2026, 2, 20),
        groupId: workId,
        memo: "이탈리안 레스토랑",
      },
      {
        title: "보드게임 카페",
        logDate: d(2026, 2, 14),
        groupId: friendId,
        memo: "발렌타인데이 모임",
      },
      {
        title: "헬스장 동료 런치",
        logDate: d(2026, 2, 8),
        groupId: acquaintId,
        memo: "샐러드 바",
      },
      {
        title: "아버지 생신 파티",
        logDate: d(2026, 1, 31),
        groupId: familyId,
        memo: "가족 레스토랑",
      },
      {
        title: "영어 스터디 그룹",
        logDate: d(2026, 1, 25),
        groupId: friendId,
        memo: "강남 스터디카페",
      },
      {
        title: "신년회",
        logDate: d(2026, 1, 10),
        groupId: workId,
        memo: "강남 레스토랑",
      },
      {
        title: "등산 모임",
        logDate: d(2026, 1, 5),
        groupId: friendId,
        memo: "북한산",
      },
      {
        title: "크리스마스 파티",
        logDate: d(2025, 12, 25),
        groupId: friendId,
        memo: "홈파티",
      },
      {
        title: "송년회",
        logDate: d(2025, 12, 20),
        groupId: workId,
        memo: "호텔 뷔페",
      },
      {
        title: "지민이 졸업 축하",
        logDate: d(2025, 12, 15),
        groupId: friendId,
      },
      { title: "가족 연말 모임", logDate: d(2025, 12, 10), groupId: familyId },
      {
        title: "야구 경기 관람",
        logDate: d(2025, 11, 22),
        groupId: friendId,
        memo: "잠실 야구장",
      },
      {
        title: "팀 프로젝트 완료 파티",
        logDate: d(2025, 11, 15),
        groupId: workId,
        memo: "피자 파티",
      },
      {
        title: "지인 집들이",
        logDate: d(2025, 11, 8),
        groupId: acquaintId,
        memo: "집들이 선물 가져감",
      },
      // ── 신규 50개 ─────────────────────────────────────────
      {
        title: "동창회 정기 모임",
        logDate: d(2026, 5, 10),
        groupId: friendId,
        memo: "강남 술집",
      },
      {
        title: "스타트업 네트워킹 파티",
        logDate: d(2026, 5, 5),
        groupId: workId,
        memo: "판교 행사장",
      },
      {
        title: "주말 캠핑",
        logDate: d(2026, 4, 26),
        groupId: friendId,
        memo: "양평 캠핑장",
      },
      { title: "봄 꽃구경 나들이", logDate: d(2026, 4, 18), groupId: familyId },
      {
        title: "테니스 동호회",
        logDate: d(2026, 4, 12),
        groupId: acquaintId,
        memo: "올림픽 공원",
      },
      {
        title: "독서 토론 모임",
        logDate: d(2026, 4, 8),
        groupId: acquaintId,
        memo: "홍대 카페",
      },
      {
        title: "요리 클래스 수업",
        logDate: d(2026, 4, 2),
        groupId: acquaintId,
        memo: "마포 쿠킹 스튜디오",
      },
      { title: "프리랜서 네트워킹", logDate: d(2026, 3, 30), groupId: workId },
      {
        title: "출판 기념 파티",
        logDate: d(2026, 3, 25),
        groupId: acquaintId,
        memo: "인사동 카페",
      },
      { title: "스터디 그룹 발표", logDate: d(2026, 3, 20), groupId: workId },
      {
        title: "생일 서프라이즈",
        logDate: d(2026, 3, 18),
        groupId: friendId,
        memo: "케이크 이벤트",
      },
      {
        title: "미술관 데이트",
        logDate: d(2026, 3, 13),
        groupId: friendId,
        memo: "서울시립미술관",
      },
      {
        title: "조깅 약속",
        logDate: d(2026, 3, 5),
        groupId: friendId,
        memo: "한강 뚝섬",
      },
      { title: "커리어 상담", logDate: d(2026, 2, 27), groupId: workId },
      {
        title: "콘서트 관람",
        logDate: d(2026, 2, 22),
        groupId: friendId,
        memo: "올림픽홀",
      },
      {
        title: "와인 파티",
        logDate: d(2026, 2, 17),
        groupId: acquaintId,
        memo: "홈파티",
      },
      {
        title: "마라톤 응원",
        logDate: d(2026, 2, 10),
        groupId: friendId,
        memo: "서울 마라톤",
      },
      {
        title: "팀 오프사이트",
        logDate: d(2026, 2, 5),
        groupId: workId,
        memo: "제주도 워케이션",
      },
      { title: "졸업 논문 지도", logDate: d(2026, 1, 28), groupId: workId },
      {
        title: "볼링 대회",
        logDate: d(2026, 1, 22),
        groupId: friendId,
        memo: "강남 볼링장",
      },
      {
        title: "새해 첫 만남",
        logDate: d(2026, 1, 3),
        groupId: friendId,
        memo: "신년 카페",
      },
      {
        title: "이사 도움",
        logDate: d(2025, 12, 28),
        groupId: acquaintId,
        memo: "이삿짐 정리 도움",
      },
      {
        title: "연말 자선 행사",
        logDate: d(2025, 12, 22),
        groupId: acquaintId,
      },
      { title: "수능 응원 방문", logDate: d(2025, 11, 13), groupId: familyId },
      {
        title: "창업 아이디어 브레인스토밍",
        logDate: d(2025, 11, 5),
        groupId: workId,
        memo: "카페 회의",
      },
      {
        title: "추석 명절 모임",
        logDate: d(2025, 10, 5),
        groupId: familyId,
        memo: "고향 방문",
      },
      {
        title: "야외 바베큐",
        logDate: d(2025, 9, 20),
        groupId: friendId,
        memo: "공원 바베큐",
      },
      { title: "프로젝트 킥오프", logDate: d(2025, 9, 2), groupId: workId },
      {
        title: "제주도 여행",
        logDate: d(2025, 8, 15),
        groupId: friendId,
        memo: "5박 6일 여행",
      },
      {
        title: "고등학교 졸업 10주년 동창회",
        logDate: d(2025, 8, 2),
        groupId: friendId,
        memo: "모교 방문",
      },
      {
        title: "스키장 여행",
        logDate: d(2025, 1, 18),
        groupId: friendId,
        memo: "강원도 스키장",
      },
      {
        title: "워크아웃 챌린지 마무리",
        logDate: d(2025, 5, 22),
        groupId: acquaintId,
      },
      {
        title: "재즈 바 방문",
        logDate: d(2025, 7, 12),
        groupId: friendId,
        memo: "이태원 재즈바",
      },
      {
        title: "글쓰기 모임",
        logDate: d(2025, 6, 30),
        groupId: acquaintId,
        memo: "온라인 진행",
      },
      {
        title: "팀 오찬",
        logDate: d(2025, 10, 25),
        groupId: workId,
        memo: "본사 구내식당",
      },
      {
        title: "봉사활동",
        logDate: d(2025, 11, 29),
        groupId: acquaintId,
        memo: "노인 복지관",
      },
      {
        title: "반려동물 카페",
        logDate: d(2025, 12, 8),
        groupId: friendId,
        memo: "강남 고양이 카페",
      },
      { title: "사진전 동반", logDate: d(2026, 1, 15), groupId: acquaintId },
      { title: "노래방 번개", logDate: d(2026, 2, 3), groupId: friendId },
      { title: "오피스 점심 미팅", logDate: d(2026, 3, 4), groupId: workId },
      {
        title: "약혼식 참석",
        logDate: d(2025, 9, 27),
        groupId: friendId,
        memo: "부산 파티홀",
      },
      {
        title: "돌잔치 참석",
        logDate: d(2025, 10, 18),
        groupId: acquaintId,
        memo: "선물 준비",
      },
      { title: "기타 합주", logDate: d(2025, 8, 25), groupId: friendId },
      { title: "홍대 클럽 나이트", logDate: d(2025, 7, 26), groupId: friendId },
      {
        title: "삼겹살 번개",
        logDate: d(2025, 6, 14),
        groupId: friendId,
        memo: "구로 삼겹살",
      },
      {
        title: "직장인 세미나",
        logDate: d(2025, 5, 30),
        groupId: workId,
        memo: "여의도 컨퍼런스",
      },
      {
        title: "등산 후 막걸리",
        logDate: d(2025, 4, 19),
        groupId: friendId,
        memo: "청계산",
      },
      {
        title: "부모님 여행 계획",
        logDate: d(2026, 5, 1),
        groupId: familyId,
        memo: "일본 여행 준비",
      },
      {
        title: "회사 창립 기념일 행사",
        logDate: d(2026, 4, 23),
        groupId: workId,
        memo: "회사 파티",
      },
      {
        title: "자전거 모임",
        logDate: d(2026, 4, 6),
        groupId: acquaintId,
        memo: "한강 자전거 길",
      },
    ])
    .returning();

  // 기록-인물 연결
  await db.insert(logPersons).values([
    // ── 기존 30개 연결 ─────────────────────────────────────
    { logId: l[0].id, personId: p[0].id },
    { logId: l[0].id, personId: p[7].id },
    { logId: l[0].id, personId: p[20].id },
    { logId: l[0].id, personId: p[25].id },
    { logId: l[0].id, personId: p[33].id },
    { logId: l[0].id, personId: p[45].id },
    { logId: l[1].id, personId: p[1].id },
    { logId: l[1].id, personId: p[4].id },
    { logId: l[1].id, personId: p[5].id },
    { logId: l[1].id, personId: p[30].id },
    { logId: l[1].id, personId: p[32].id },
    { logId: l[2].id, personId: p[2].id },
    { logId: l[2].id, personId: p[6].id },
    { logId: l[2].id, personId: p[9].id },
    { logId: l[2].id, personId: p[12].id },
    { logId: l[3].id, personId: p[1].id },
    { logId: l[3].id, personId: p[4].id },
    { logId: l[3].id, personId: p[15].id },
    { logId: l[3].id, personId: p[30].id },
    { logId: l[3].id, personId: p[37].id },
    { logId: l[4].id, personId: p[0].id },
    { logId: l[4].id, personId: p[25].id },
    { logId: l[5].id, personId: p[3].id },
    { logId: l[5].id, personId: p[34].id },
    { logId: l[6].id, personId: p[2].id },
    { logId: l[6].id, personId: p[16].id },
    { logId: l[7].id, personId: p[1].id },
    { logId: l[7].id, personId: p[4].id },
    { logId: l[7].id, personId: p[8].id },
    { logId: l[7].id, personId: p[11].id },
    { logId: l[7].id, personId: p[32].id },
    { logId: l[7].id, personId: p[35].id },
    { logId: l[7].id, personId: p[41].id },
    { logId: l[8].id, personId: p[0].id },
    { logId: l[8].id, personId: p[7].id },
    { logId: l[8].id, personId: p[20].id },
    { logId: l[9].id, personId: p[4].id },
    { logId: l[9].id, personId: p[5].id },
    { logId: l[10].id, personId: p[1].id },
    { logId: l[10].id, personId: p[8].id },
    { logId: l[10].id, personId: p[24].id },
    { logId: l[10].id, personId: p[30].id },
    { logId: l[10].id, personId: p[43].id },
    { logId: l[11].id, personId: p[2].id },
    { logId: l[11].id, personId: p[6].id },
    { logId: l[11].id, personId: p[9].id },
    { logId: l[11].id, personId: p[16].id },
    { logId: l[11].id, personId: p[23].id },
    { logId: l[11].id, personId: p[31].id },
    { logId: l[11].id, personId: p[36].id },
    { logId: l[12].id, personId: p[1].id },
    { logId: l[12].id, personId: p[5].id },
    { logId: l[12].id, personId: p[11].id },
    { logId: l[12].id, personId: p[18].id },
    { logId: l[12].id, personId: p[30].id },
    { logId: l[12].id, personId: p[37].id },
    { logId: l[12].id, personId: p[46].id },
    { logId: l[13].id, personId: p[0].id },
    { logId: l[13].id, personId: p[7].id },
    { logId: l[13].id, personId: p[25].id },
    { logId: l[14].id, personId: p[3].id },
    { logId: l[14].id, personId: p[10].id },
    { logId: l[14].id, personId: p[17].id },
    { logId: l[15].id, personId: p[0].id },
    { logId: l[15].id, personId: p[7].id },
    { logId: l[15].id, personId: p[13].id },
    { logId: l[15].id, personId: p[20].id },
    { logId: l[15].id, personId: p[25].id },
    { logId: l[15].id, personId: p[33].id },
    { logId: l[15].id, personId: p[39].id },
    { logId: l[15].id, personId: p[45].id },
    { logId: l[16].id, personId: p[2].id },
    { logId: l[16].id, personId: p[6].id },
    { logId: l[16].id, personId: p[19].id },
    { logId: l[16].id, personId: p[26].id },
    { logId: l[16].id, personId: p[36].id },
    { logId: l[16].id, personId: p[44].id },
    { logId: l[17].id, personId: p[1].id },
    { logId: l[17].id, personId: p[4].id },
    { logId: l[17].id, personId: p[5].id },
    { logId: l[17].id, personId: p[18].id },
    { logId: l[17].id, personId: p[28].id },
    { logId: l[17].id, personId: p[30].id },
    { logId: l[18].id, personId: p[10].id },
    { logId: l[18].id, personId: p[17].id },
    { logId: l[19].id, personId: p[0].id },
    { logId: l[19].id, personId: p[7].id },
    { logId: l[19].id, personId: p[13].id },
    { logId: l[19].id, personId: p[20].id },
    { logId: l[19].id, personId: p[25].id },
    { logId: l[20].id, personId: p[1].id },
    { logId: l[20].id, personId: p[5].id },
    { logId: l[20].id, personId: p[24].id },
    { logId: l[21].id, personId: p[2].id },
    { logId: l[21].id, personId: p[16].id },
    { logId: l[21].id, personId: p[29].id },
    { logId: l[21].id, personId: p[31].id },
    { logId: l[21].id, personId: p[49].id },
    { logId: l[22].id, personId: p[3].id },
    { logId: l[22].id, personId: p[8].id },
    { logId: l[22].id, personId: p[21].id },
    { logId: l[22].id, personId: p[24].id },
    { logId: l[23].id, personId: p[1].id },
    { logId: l[23].id, personId: p[4].id },
    { logId: l[23].id, personId: p[5].id },
    { logId: l[23].id, personId: p[11].id },
    { logId: l[23].id, personId: p[28].id },
    { logId: l[23].id, personId: p[32].id },
    { logId: l[23].id, personId: p[41].id },
    { logId: l[24].id, personId: p[2].id },
    { logId: l[24].id, personId: p[6].id },
    { logId: l[24].id, personId: p[16].id },
    { logId: l[24].id, personId: p[19].id },
    { logId: l[24].id, personId: p[31].id },
    { logId: l[24].id, personId: p[36].id },
    { logId: l[25].id, personId: p[1].id },
    { logId: l[25].id, personId: p[4].id },
    { logId: l[25].id, personId: p[5].id },
    { logId: l[26].id, personId: p[0].id },
    { logId: l[26].id, personId: p[7].id },
    { logId: l[26].id, personId: p[13].id },
    { logId: l[26].id, personId: p[25].id },
    { logId: l[27].id, personId: p[3].id },
    { logId: l[27].id, personId: p[8].id },
    { logId: l[27].id, personId: p[21].id },
    { logId: l[27].id, personId: p[43].id },
    { logId: l[28].id, personId: p[2].id },
    { logId: l[28].id, personId: p[6].id },
    { logId: l[28].id, personId: p[23].id },
    { logId: l[28].id, personId: p[31].id },
    { logId: l[28].id, personId: p[44].id },
    { logId: l[29].id, personId: p[10].id },
    { logId: l[29].id, personId: p[17].id },
    { logId: l[29].id, personId: p[22].id },
    { logId: l[29].id, personId: p[27].id },
    { logId: l[29].id, personId: p[34].id },
    { logId: l[29].id, personId: p[42].id },
    // ── 신규 50개 연결 ─────────────────────────────────────
    { logId: l[30].id, personId: p[1].id },
    { logId: l[30].id, personId: p[4].id },
    { logId: l[30].id, personId: p[60].id },
    { logId: l[30].id, personId: p[62].id },
    { logId: l[30].id, personId: p[64].id },
    { logId: l[31].id, personId: p[31].id },
    { logId: l[31].id, personId: p[49].id },
    { logId: l[31].id, personId: p[65].id },
    { logId: l[31].id, personId: p[72].id },
    { logId: l[32].id, personId: p[1].id },
    { logId: l[32].id, personId: p[8].id },
    { logId: l[32].id, personId: p[62].id },
    { logId: l[32].id, personId: p[77].id },
    { logId: l[33].id, personId: p[0].id },
    { logId: l[33].id, personId: p[7].id },
    { logId: l[33].id, personId: p[25].id },
    { logId: l[33].id, personId: p[80].id },
    { logId: l[34].id, personId: p[53].id },
    { logId: l[34].id, personId: p[59].id },
    { logId: l[34].id, personId: p[74].id },
    { logId: l[35].id, personId: p[53].id },
    { logId: l[35].id, personId: p[56].id },
    { logId: l[35].id, personId: p[83].id },
    { logId: l[35].id, personId: p[91].id },
    { logId: l[36].id, personId: p[56].id },
    { logId: l[36].id, personId: p[63].id },
    { logId: l[36].id, personId: p[78].id },
    { logId: l[37].id, personId: p[47].id },
    { logId: l[37].id, personId: p[72].id },
    { logId: l[37].id, personId: p[86].id },
    { logId: l[38].id, personId: p[53].id },
    { logId: l[38].id, personId: p[63].id },
    { logId: l[38].id, personId: p[81].id },
    { logId: l[39].id, personId: p[50].id },
    { logId: l[39].id, personId: p[51].id },
    { logId: l[39].id, personId: p[54].id },
    { logId: l[40].id, personId: p[30].id },
    { logId: l[40].id, personId: p[50].id },
    { logId: l[40].id, personId: p[66].id },
    { logId: l[41].id, personId: p[30].id },
    { logId: l[41].id, personId: p[73].id },
    { logId: l[41].id, personId: p[85].id },
    { logId: l[42].id, personId: p[62].id },
    { logId: l[42].id, personId: p[77].id },
    { logId: l[42].id, personId: p[97].id },
    { logId: l[43].id, personId: p[29].id },
    { logId: l[43].id, personId: p[31].id },
    { logId: l[43].id, personId: p[82].id },
    { logId: l[44].id, personId: p[30].id },
    { logId: l[44].id, personId: p[52].id },
    { logId: l[44].id, personId: p[64].id },
    { logId: l[45].id, personId: p[53].id },
    { logId: l[45].id, personId: p[56].id },
    { logId: l[45].id, personId: p[67].id },
    { logId: l[46].id, personId: p[32].id },
    { logId: l[46].id, personId: p[62].id },
    { logId: l[46].id, personId: p[77].id },
    { logId: l[47].id, personId: p[31].id },
    { logId: l[47].id, personId: p[36].id },
    { logId: l[47].id, personId: p[58].id },
    { logId: l[47].id, personId: p[72].id },
    { logId: l[48].id, personId: p[41].id },
    { logId: l[48].id, personId: p[54].id },
    { logId: l[48].id, personId: p[82].id },
    { logId: l[49].id, personId: p[1].id },
    { logId: l[49].id, personId: p[60].id },
    { logId: l[49].id, personId: p[62].id },
    { logId: l[49].id, personId: p[77].id },
    { logId: l[50].id, personId: p[30].id },
    { logId: l[50].id, personId: p[32].id },
    { logId: l[50].id, personId: p[50].id },
    { logId: l[51].id, personId: p[63].id },
    { logId: l[51].id, personId: p[81].id },
    { logId: l[51].id, personId: p[92].id },
    { logId: l[52].id, personId: p[53].id },
    { logId: l[52].id, personId: p[74].id },
    { logId: l[52].id, personId: p[81].id },
    { logId: l[53].id, personId: p[0].id },
    { logId: l[53].id, personId: p[25].id },
    { logId: l[53].id, personId: p[33].id },
    { logId: l[54].id, personId: p[31].id },
    { logId: l[54].id, personId: p[49].id },
    { logId: l[54].id, personId: p[65].id },
    { logId: l[55].id, personId: p[0].id },
    { logId: l[55].id, personId: p[7].id },
    { logId: l[55].id, personId: p[25].id },
    { logId: l[55].id, personId: p[33].id },
    { logId: l[55].id, personId: p[39].id },
    { logId: l[55].id, personId: p[80].id },
    { logId: l[56].id, personId: p[1].id },
    { logId: l[56].id, personId: p[4].id },
    { logId: l[56].id, personId: p[30].id },
    { logId: l[56].id, personId: p[32].id },
    { logId: l[57].id, personId: p[2].id },
    { logId: l[57].id, personId: p[31].id },
    { logId: l[57].id, personId: p[44].id },
    { logId: l[57].id, personId: p[58].id },
    { logId: l[58].id, personId: p[1].id },
    { logId: l[58].id, personId: p[30].id },
    { logId: l[58].id, personId: p[32].id },
    { logId: l[58].id, personId: p[52].id },
    { logId: l[59].id, personId: p[60].id },
    { logId: l[59].id, personId: p[62].id },
    { logId: l[59].id, personId: p[64].id },
    { logId: l[59].id, personId: p[66].id },
    { logId: l[60].id, personId: p[8].id },
    { logId: l[60].id, personId: p[32].id },
    { logId: l[60].id, personId: p[77].id },
    { logId: l[61].id, personId: p[59].id },
    { logId: l[61].id, personId: p[67].id },
    { logId: l[61].id, personId: p[92].id },
    { logId: l[62].id, personId: p[30].id },
    { logId: l[62].id, personId: p[52].id },
    { logId: l[62].id, personId: p[73].id },
    { logId: l[63].id, personId: p[57].id },
    { logId: l[63].id, personId: p[68].id },
    { logId: l[63].id, personId: p[91].id },
    { logId: l[64].id, personId: p[2].id },
    { logId: l[64].id, personId: p[51].id },
    { logId: l[64].id, personId: p[54].id },
    { logId: l[64].id, personId: p[79].id },
    { logId: l[65].id, personId: p[56].id },
    { logId: l[65].id, personId: p[81].id },
    { logId: l[65].id, personId: p[92].id },
    { logId: l[66].id, personId: p[30].id },
    { logId: l[66].id, personId: p[52].id },
    { logId: l[66].id, personId: p[55].id },
    { logId: l[66].id, personId: p[57].id },
    { logId: l[67].id, personId: p[63].id },
    { logId: l[67].id, personId: p[74].id },
    { logId: l[67].id, personId: p[81].id },
    { logId: l[68].id, personId: p[1].id },
    { logId: l[68].id, personId: p[50].id },
    { logId: l[68].id, personId: p[60].id },
    { logId: l[68].id, personId: p[62].id },
    { logId: l[69].id, personId: p[51].id },
    { logId: l[69].id, personId: p[54].id },
    { logId: l[69].id, personId: p[76].id },
    { logId: l[70].id, personId: p[11].id },
    { logId: l[70].id, personId: p[85].id },
    { logId: l[70].id, personId: p[87].id },
    { logId: l[71].id, personId: p[17].id },
    { logId: l[71].id, personId: p[63].id },
    { logId: l[71].id, personId: p[71].id },
    { logId: l[72].id, personId: p[60].id },
    { logId: l[72].id, personId: p[62].id },
    { logId: l[72].id, personId: p[77].id },
    { logId: l[73].id, personId: p[32].id },
    { logId: l[73].id, personId: p[52].id },
    { logId: l[73].id, personId: p[66].id },
    { logId: l[73].id, personId: p[80].id },
    { logId: l[74].id, personId: p[1].id },
    { logId: l[74].id, personId: p[8].id },
    { logId: l[74].id, personId: p[24].id },
    { logId: l[74].id, personId: p[32].id },
    { logId: l[75].id, personId: p[51].id },
    { logId: l[75].id, personId: p[65].id },
    { logId: l[75].id, personId: p[76].id },
    { logId: l[75].id, personId: p[82].id },
    { logId: l[76].id, personId: p[8].id },
    { logId: l[76].id, personId: p[21].id },
    { logId: l[76].id, personId: p[62].id },
    { logId: l[77].id, personId: p[0].id },
    { logId: l[77].id, personId: p[25].id },
    { logId: l[77].id, personId: p[33].id },
    { logId: l[78].id, personId: p[2].id },
    { logId: l[78].id, personId: p[31].id },
    { logId: l[78].id, personId: p[65].id },
    { logId: l[78].id, personId: p[76].id },
    { logId: l[79].id, personId: p[59].id },
    { logId: l[79].id, personId: p[74].id },
    { logId: l[79].id, personId: p[92].id },
  ]);

  // 할 일 60개 — 사분면별 균형 배분
  await db.insert(todos).values([
    // ── do (즉시 처리) 15개 ────────────────────────────────
    { title: "프로젝트 기획안 제출", quadrant: "do" },
    { title: "연간 보고서 작성", quadrant: "do" },
    { title: "중요 거래처 미팅 준비", quadrant: "do" },
    { title: "버그 수정 PR 제출", quadrant: "do" },
    { title: "이번 달 가계부 정리", quadrant: "do" },
    { title: "운전면허 갱신 신청", quadrant: "do" },
    { title: "건강검진 예약", quadrant: "do" },
    { title: "급여명세서 확인", quadrant: "do" },
    { title: "시장 분석 보고서 작성", quadrant: "do" },
    { title: "법인카드 영수증 제출", quadrant: "do" },
    { title: "사이드 프로젝트 데모 준비", quadrant: "do" },
    { title: "투자 제안서 수정", quadrant: "do" },
    { title: "비자 서류 준비", quadrant: "do" },
    { title: "차량 보험 갱신", quadrant: "do" },
    { title: "고객 피드백 정리", quadrant: "do" },
    // ── schedule (일정 잡기) 15개 ──────────────────────────
    { title: "독서 모임 일정 잡기", quadrant: "schedule" },
    { title: "친구 생일 파티 계획", quadrant: "schedule" },
    { title: "가족 여행 숙소 예약", quadrant: "schedule" },
    { title: "치과 정기검진 예약", quadrant: "schedule" },
    { title: "헬스 PT 등록", quadrant: "schedule" },
    { title: "팀빌딩 행사 기획", quadrant: "schedule" },
    { title: "월간 팀 회의 일정 확정", quadrant: "schedule" },
    { title: "여름 휴가 계획 세우기", quadrant: "schedule" },
    { title: "여름 인턴 면접 일정", quadrant: "schedule" },
    { title: "부모님 생신 식당 예약", quadrant: "schedule" },
    { title: "연간 건강보험 갱신", quadrant: "schedule" },
    { title: "동창회 총무 선거", quadrant: "schedule" },
    { title: "부서 야유회 장소 예약", quadrant: "schedule" },
    { title: "반기 성과 리뷰 일정", quadrant: "schedule" },
    { title: "필라테스 수강 등록", quadrant: "schedule" },
    // ── delegate (위임) 15개 ───────────────────────────────
    { title: "팀원에게 보고서 취합 요청", quadrant: "delegate" },
    { title: "동생한테 택배 수령 부탁", quadrant: "delegate" },
    { title: "디자인팀에 시안 제작 요청", quadrant: "delegate" },
    { title: "총무팀에 비품 신청", quadrant: "delegate" },
    { title: "회계팀에 영수증 처리 요청", quadrant: "delegate" },
    { title: "고객 문의 후임자에게 이관", quadrant: "delegate" },
    { title: "인턴에게 자료 조사 맡기기", quadrant: "delegate" },
    { title: "동료에게 회의록 작성 부탁", quadrant: "delegate" },
    { title: "법무팀에 계약서 검토 의뢰", quadrant: "delegate" },
    { title: "IT팀에 노트북 수리 요청", quadrant: "delegate" },
    { title: "후배에게 주간 보고 작성 맡기기", quadrant: "delegate" },
    { title: "행정팀에 출장 경비 처리 요청", quadrant: "delegate" },
    { title: "고객사에 견적서 발송 요청", quadrant: "delegate" },
    { title: "동생에게 부모님 선물 구매 부탁", quadrant: "delegate" },
    { title: "외주 번역가에게 문서 번역 의뢰", quadrant: "delegate" },
    // ── eliminate (제거) 15개 ──────────────────────────────
    { title: "불필요한 구독 서비스 정리", quadrant: "eliminate" },
    { title: "쓰지 않는 앱 삭제", quadrant: "eliminate" },
    { title: "오래된 이메일 정리", quadrant: "eliminate" },
    { title: "낡은 옷가지 정리", quadrant: "eliminate" },
    { title: "안 보는 유튜브 채널 구독 취소", quadrant: "eliminate" },
    { title: "자동 갱신 멤버십 해지", quadrant: "eliminate" },
    { title: "안 읽은 뉴스레터 정리", quadrant: "eliminate" },
    { title: "중복된 클라우드 저장소 정리", quadrant: "eliminate" },
    { title: "오래된 메모 앱 데이터 삭제", quadrant: "eliminate" },
    { title: "쓰지 않는 게임 계정 탈퇴", quadrant: "eliminate" },
    { title: "배달앱 자동결제 정리", quadrant: "eliminate" },
    { title: "안 입는 책 중고 판매", quadrant: "eliminate" },
    { title: "낡은 전자기기 처분", quadrant: "eliminate" },
    { title: "사용 안 하는 소셜 계정 비활성화", quadrant: "eliminate" },
    { title: "반복되는 불필요한 회의 없애기", quadrant: "eliminate" },
  ]);

  // 메모 60개
  await db.insert(memos).values([
    // ── 기존 30개 ─────────────────────────────────────────
    { content: "민수 형한테 빌린 책 돌려줘야 함" },
    { content: "6월 가족 여행 숙소 알아보기 — 제주도 or 강릉" },
    { content: "지원이 좋아하는 음식: 파스타, 티라미수" },
    { content: "승준 씨 생일 체크해야 함 (4월)" },
    { content: "수진 팀장 커피 취향: 아메리카노, 샷 추가" },
    { content: "현우 새 직장 취업 축하 선물 준비하기" },
    { content: "다은이한테 빌려준 우산 돌려받기" },
    { content: '지민이 추천해준 책: "아무것도 하지 않는 시간의 힘"' },
    { content: "예린 언니 아이 이름: 서윤 (3살)" },
    { content: "도현이 헬스 루틴 참고해보기" },
    { content: "민지 대리 업무 스타일: 명확한 문서 선호" },
    { content: "성호 씨 고향: 전주" },
    { content: "주연이 졸업 후 취직 예정 — 위로 메시지 보내기" },
    { content: "재원이 추천 맛집: 강남 스시집" },
    { content: "예지 동생 대입 합격 — 선물 생각해두기" },
    { content: "민혁이 최근 스타트업 창업 — 관심 가져주기" },
    { content: "아연이 전공: 심리학, 대학원 진학 고민 중" },
    { content: "승현 부장 취미: 골프, 등산" },
    { content: "소영 씨 반려견 이름: 콩이" },
    { content: "다현이 아토피 있어서 꽃 선물 주의" },
    { content: "지훈 씨 채식주의자 — 식당 예약 시 주의" },
    { content: "세연 언니 답례 선물 생각해두기" },
    { content: "현준이 해외 취업 준비 중 — 캐나다 목표" },
    { content: "지수 7월 유럽 배낭여행 계획 중" },
    { content: "해린 씨 사이드 프로젝트 같이 검토 요청받음" },
    { content: "태민이 전역 기념 파티 계획하기" },
    { content: "수빈 어머니 선호 선물: 과일 or 건강식품" },
    { content: "유진 씨 마케팅 인사이트 정기 공유 요청" },
    { content: "지후 씨 독서 취향: SF, 철학 서적" },
    { content: "채원이 유학 고민 중 — 조언 요청 받음" },
    // ── 신규 30개 ─────────────────────────────────────────
    { content: "현아 좋아하는 카페 브랜드: 블루보틀" },
    { content: "준호 씨 알레르기: 견과류 주의" },
    { content: "민서 여행 목표: 동남아 배낭여행" },
    { content: "유진 씨 독서 모임 매월 셋째 주 토요일" },
    { content: "현준 씨(정) 운동: 헬스, 주 5회" },
    { content: "소영이 반려묘 이름: 달이" },
    { content: "진호 씨 앱 출시 예정 — 베타 테스터 요청받음" },
    { content: "수연이 유학 장학금 결과 기다리는 중 — 응원 연락하기" },
    { content: "동훈 씨 선호 미팅 시간: 오전" },
    { content: "조민수 씨 고향: 부산, 자주 내려감" },
    { content: "지호 새 연인 생김 — 축하 메시지 보내기" },
    { content: "하은 씨 업무 스타일: 꼼꼼한 문서 정리" },
    { content: "배준혁 유럽 배낭 여행 중 — 이탈리아 현재 위치" },
    { content: "소희 씨 요가 클래스 소개받기로 함" },
    { content: "류민아 최근 취업 성공 — 축하 선물 준비" },
    { content: "승훈 씨 관심 분야: AI 스타트업 투자" },
    { content: "남은지 고민: 대학원 진학 vs 취업" },
    { content: "마준혁 씨 게임 ID 교환 — 같이 하기로 함" },
    { content: "노현아 최근 이사함 — 집들이 초대받음" },
    { content: "진수 씨 커피 취향: 에스프레소 더블샷" },
    { content: "성민재 추천 맛집: 합정 파스타집" },
    { content: "우다영 씨 꽃다발 받는 것 좋아함 — 기념일 선물 참고" },
    { content: "민서준 씨 책 추천: 《린 스타트업》" },
    { content: "표지연 악기 배우는 중: 우쿨렐레" },
    { content: "권태윤 씨 사진전 준비 중 — 오프닝 초대 예정" },
    { content: "장채린 절친 결혼 예정 — 6월 청첩장 올 것 같음" },
    { content: "한수현 씨 이직 고민 — 조언 구하러 연락옴" },
    { content: "임지훈 작년 부상 회복 완료 — 다시 테니스 시작" },
    { content: "윤채연 씨 도자기 공방 시작 — 작품 선물 예정" },
    { content: "강진우 씨 보안 최신 트렌드 공유해준다 했음" },
  ]);
}
